author_controller_get:
    path: /api/author
    controller: App\Authors\Infrastructure\Controllers\AuthorsGetController
    methods:  [GET]

author_controller_get_id:
    path: /api/author/{id}
    controller: App\Authors\Infrastructure\Controllers\AuthorGetController
    methods:  [GET]

author_controller_post:
    path: /api/author
    controller: App\Authors\Infrastructure\Controllers\AuthorsPostController
    methods:  [POST] 

author_controller_delete:
    path: /api/author/{id}
    controller: App\Authors\Infrastructure\Controllers\AuthorsDeleteController
    methods:  [DELETE] 